# Generated by Django 4.2.20 on 2025-05-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scene',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
